version: "3.8"
networks:
  default: 
    name: remark
services:
  database:
    container_name: database
    image: postgres:latest
    restart: always
    environment:
      - POSTGRES_USER=jens
      - POSTGRES_PASSWORD=ch0col4te
      - POSTGRES_DB=remark
    ports:
      - "5432:5432"
    volumes:
      - ./postgres-data:/var/lib/postgresql/data