version: "3.8"
services:
  database:
    image: postgres:latest
    restart: always
    environment:
      - POSTGRES_USER=jens
      - POSTGRES_PASSWORD=ch0col4te
      - POSTGRES_DB=remark
    ports:
      - "5432:5432"
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
  app:
    build: .
    depends_on:
      - database
    ports:
      - "3000:3000"
    environment:
      - DATABASE_URL=postgresql://jens:ch0col4te@database:5432/remark
      - SESSION_SECRET=foobar
